version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    network_mode: bridge
    restart: always
    ports:
      - 4444:4444
    volumes:
      - "./config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    container_name: selenoid-ui
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - 8080:8080
    command:
      - '--selenoid-uri'
      - 'http://selenoid:4444'